// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YsRKXGnf70DLVC-IafiIsx7cT19pJ1k',
    appId: '1:226748629083:web:31a917dd398d92d0673f7e',
    messagingSenderId: '226748629083',
    projectId: 'smart-note-d885d',
    authDomain: 'smart-note-d885d.firebaseapp.com',
    storageBucket: 'smart-note-d885d.appspot.com',
    measurementId: 'G-JPCNDV8H0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-ax6rm3MM75f3h83m88sV0OwYacWHno',
    appId: '1:226748629083:android:50d9ed2a663b2ad5673f7e',
    messagingSenderId: '226748629083',
    projectId: 'smart-note-d885d',
    storageBucket: 'smart-note-d885d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNOm7zuNrApJF9fs-oUMuDktvejONCbY',
    appId: '1:226748629083:ios:5ea87a9cb57d771f673f7e',
    messagingSenderId: '226748629083',
    projectId: 'smart-note-d885d',
    storageBucket: 'smart-note-d885d.appspot.com',
    iosBundleId: 'com.example.smartnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNOm7zuNrApJF9fs-oUMuDktvejONCbY',
    appId: '1:226748629083:ios:a7a9d449f69927ae673f7e',
    messagingSenderId: '226748629083',
    projectId: 'smart-note-d885d',
    storageBucket: 'smart-note-d885d.appspot.com',
    iosBundleId: 'com.example.smartnote.RunnerTests',
  );
}
